-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.email_verification
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    CONSTRAINT email_verification_pkey PRIMARY KEY (id),
    CONSTRAINT email_verification_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.mfa
(
    user_id uuid NOT NULL,
    totp_secret_encrypted text COLLATE pg_catalog."default" NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT mfa_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.mfa_recovery_codes
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    code_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    used_at timestamp with time zone,
    CONSTRAINT mfa_recovery_codes_pkey PRIMARY KEY (id),
    CONSTRAINT mfa_recovery_codes_code_hash_key UNIQUE (code_hash)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.profile
(
    user_id uuid NOT NULL,
    overall_score double precision NOT NULL,
    projects_score double precision NOT NULL,
    experience_score double precision NOT NULL,
    education_score double precision NOT NULL,
    skills_score double precision NOT NULL,
    profile_json jsonb NOT NULL,
    name_tsv tsvector,
    location_tsv tsvector,
    experience_tsv tsvector,
    education_tsv tsvector,
    CONSTRAINT profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    ip character varying COLLATE pg_catalog."default",
    agent text COLLATE pg_catalog."default",
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email citext COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.email_verification
    ADD CONSTRAINT fk_uuid_user_id_email FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.mfa
    ADD CONSTRAINT mfa_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS mfa_pkey
    ON public.mfa(user_id);


ALTER TABLE IF EXISTS public.mfa_recovery_codes
    ADD CONSTRAINT mfa_recovery_codes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mfa_recovery_user
    ON public.mfa_recovery_codes(user_id);


ALTER TABLE IF EXISTS public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_prt_unused_user
    ON public.password_reset_tokens(user_id);


ALTER TABLE IF EXISTS public.profile
    ADD CONSTRAINT fk_id_uuid_profile FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS profile_pkey
    ON public.profile(user_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_not_revoked_user
    ON public.sessions(user_id);

END;